### ISSUE TITLE
Is it at all possible to add SelBlocks as user-extensions.js to selenium-server?

### ISSUE THREAD

**Issue by TomaszDom** [refactoror/SelBlocks#10]
I've tried adding all the *.js scripts to selenium server, but the server freezes when it tries running htmlsuites interactively or otherwise. Is it all possible to add these scripts to selenium server to make a custom build that supports all this new wonderful functionality? Testing in Selenium IDE is one thing, but it would be fantastic to be able to run using the server (and automate using Jenkins, etc.)

**Comment by refactoror** [comment]
SelBlocks 2.1 introduces support for Selenium Server. Get the extension file here: https://raw.githubusercontent.com/refactoror/SelBlocks/master/user-extensions.js

Initial browser support is for firefox, googlechrome, and opera.

**Comment by reegen** [comment]
Hi,

I saw in your Wiki (http://refactoror.wikia.com/wiki/Selblocks_Reference) that you posted that "this feature has a significant bug, and is not currently supported.":

![image](https://cloud.githubusercontent.com/assets/16291629/22623375/102e358c-eb40-11e6-9125-6f5ef945c0f3.png)

Is it still with the bug, or you already fixed it?
