### ISSUE TITLE
Limiting the amount of runs

### ISSUE THREAD

**Issue by UTO-QA** [refactoror/SelBlocks#22]
Hi, if I use a file that has 100 records on it and I want to only run 5 of them then have the automation stop, how would I do that with SelBlocks? Thanks

**Comment by apodhajsky** [comment]
use break command in loop -> if (condition) then break

**Comment by refactoror** [comment]
if/break will work. Also, note that a condition can be specified on the `break` command itself. See Examples of Use section in the docs: http://refactoror.wikia.com/wiki/Selblocks_Reference
