### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by MadejaPeter** [refactoror/SelBlocks#23]
Hi, 
i am pretty new in selenium IDE. I installed SelBlocks plugin to Firefox, but i am not able to use If, For or other commands. I receive error message: [error] Unexpected Exception: TypeError: blockDefs is null. 
Can you help me with this pls?

Thanks, Peter

**Comment by refactoror** [comment]
It's hard to know what might be going on without any information about your setup. But a guess would be that you could have a conflicting plugin installed. Please see the docs: http://refactoror.wikia.com/wiki/Selblocks_Reference#Compatibility

**Comment by MadejaPeter** [comment]
I remove Selenium IDE: Flow Control add-on and it finally works. Do you know why there is a problem with Flow control?

**Comment by refactoror** [comment]
I will rework the conflict explanation in the Compatibility section. Bascially, flowControl heavy-handedly modifies an internal Selenium pointer, which disrupts any other plugins that require intitialization before tests run.

**Comment by MadejaPeter** [comment]
Thanks for explanation. I have one more question. Is it possible to use nested if with SelBlocks? Or only option is to use goto?

**Comment by refactoror** [comment]
Nest away. It's called SelBlocks because the block structures behave as in any other programming language...
