### ISSUE TITLE
Change of context (location) in a try block causes false-negative checks

### ISSUE THREAD

**Issue by Zorvalt** [refactoror/SelBlocks#26]
Hi,

I think I might have found a bug : When I change my location inside a try block, all locators fail to find my elements.

The following code works outside a try block but fails when inside one :

assertElementPresent | xpath=(somePath)
clickAndWait | xpath=(somePath)
assertText | css=h1.page-title | My Title

I get the error : [error] Element xpath=(somePath) not found

It looks like the try block keeps the initial context or something like that.
I hope my comment is complete and will be usefull.

Zorvalt

**Comment by refactoror** [comment]
Selblocks version? Selenium version? Firefox version?

**Comment by refactoror** [comment]
Cannot be reproduced. Nor is the problematic try block provided.
