### ISSUE TITLE
"Not a Boolean Expression" error when using loadXmlVars - StoredVars are loaded, however Test Fails

### ISSUE THREAD

**Issue by patrick-ryan1** [refactoror/SelBlocks#27]
Hello,

Using latest versions of Firefox, Selenium IDE and SelBlock{}.  When trying to loadXmlVars with only a file-path value, receiving “Not a Boolean Expression” error. There is no value in ?selector-expression listed in test case to resolve to Not a Boolean and the variables are loaded in Selenium IDE.  The Test Fails however so further execution is not possible.

Selenium Test Case – 
loadXmlVars file://C:\ test.xml 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://test.salesforce.com/" />
<title>New Test</title>
</head>
<body>

<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
    <td>loadXmlVars</td>
    <td>file://C:\Users\usparya\Documents\GitHub\temp\vartest.xml</td>
    <td></td>
</tr>
</tbody></table>

</body>
</html>

Test Data

<testdata>
<vars role="superuser" userid="dilbert"/>
</testdata>

Debug Log
•  [info] Executing: |loadXmlVars | file://C:\test.xml| | 
• [debug] Command found, going to execute loadXmlVars 
• [debug] [selblocks] FileReader() using URL to get file 'file://C:\test.xml' 
• [info] [selblocks] Reading from: file://C:\test.xml 
• [debug] [selblocks] 1) <vars user="test"/> 
• [error] [selblocks] Error @1: [loadXmlVars|file://C:\test.xml], is not a boolean expression 
• [warn] [selblocks] **Stack Trace** 
• [error] Unexpected Exception: Error: @1: [loadXmlVars|file://C:\test.xml], is not a boolean expression. 
• [debug] testComplete: failed=false 

Configuration
1.  Firefox 48 for Windows (7)
2.  Selenium IDE 2.9.1 loaded – restart Firefox
3.  SelBlock{} 2.1 Extensions Loaded

**Comment by HSI-Ron** [comment]
Hi,
I'm having the same issue, how did you resolve it?

Thanks,
Ron

**Comment by refactoror** [comment]
It is likely that the selector-expression, (the Target field), contained whitespace, or unprintable character(s). The non-empty, invalid expression is included in the error message immediately before 'is not'.

It should either be empty, or it should contain an expression that evaluates to a boolean as each entry is processed.

**Comment by mirao** [comment]
I have the same issue with this command (I didn't type any character into selector - value):
```
<tr>
	<td>loadXmlVars</td>
	<td>host.xml</td>
	<td></td>
</tr>
```

### Log:
`[error] @/home/mira/workspace/bela/trunk/selenium_ide/login/openLoginScreen.html: 2: [loadXmlVars|host.xml]: , is not a boolean expression `

### Workaround:
```
<tr>
	<td>loadXmlVars</td>
	<td>host.xml</td>
	<td>true</td>
</tr>
```

### Used SW:

- Ubuntu 16.10, Firefox 51.0.1, Selenium IDE 2.9.1.1, SeLite SelBlocks Global 2.69
