### ISSUE TITLE
Call function between test cases

### ISSUE THREAD

**Issue by spasova** [refactoror/SelBlocks#28]
Hello,

I installed SelBlocks 2.1.
I tried to call function A, defined in test case1 from test case2, but I get the following error:
[error] [selblocks] Error @1: [call|aaa] Cannot branch to non-existent command @2
[warn] [selblocks] **Stack Trace**
[error] Unexpected Exception: Error: @1: [call|aaa] Cannot branch to non-existent command @2. 
[info] Test case failed 

I do not know what I am doing wrong.
Test cases are attached.
[Login.txt](https://github.com/refactoror/SelBlocks/files/254841/Login.txt)

Thank you,
Olya Spasova

**Comment by refactoror** [comment]
Sorry, that is not supported. See: http://refactoror.wikia.com/wiki/Selblocks_Reference#Limitations

**Comment by spasova** [comment]
Thank you for the quick response.

Regards,
Olya
