### ISSUE TITLE
Error Selenium SelBlocks

### ISSUE THREAD

**Issue by blancoleandro13** [refactoror/SelBlocks#30]
I have this problem with selblocks, I want to use the IF and I can not. I do not know what to do

![image](https://cloud.githubusercontent.com/assets/21369579/18143171/5316fd18-6f97-11e6-82bf-7c484b458e7b.png)

![image](https://cloud.githubusercontent.com/assets/21369579/18143186/64759542-6f97-11e6-860d-889bce5d22e2.png)

**Comment by refactoror** [comment]
When does this error occur? Selblocks does not have anything that references globalOverlay.js.  What version of Firefox are you using? What version of Selenium? What other plugins are installed? Do you reference globalOverlay.js in your web application perhaps?

**Comment by blancoleandro13** [comment]
My Selenium Version is 2.9.1
Firefox mozilla 48.0.2
Plugin Installed : Only Selblocks
Selenium Core Extension : CSVRead_Selenium-IDE.js

I do not know if my web application has "reference globalOverlay.js" and this error when giving procude "play" or it will not let me start

Thanks  for your time

**Comment by refactoror** [comment]
I'm not able to reproduce this error using the versions of software that you describe. I have the en-US version of Firefox running on Windows 10. Of course I don't have your test script nor the application that you are testing.

I think you need to find the simplest case that causes the error. Start with with a a very simple if/endIf block. Also, has this script worked in the past? Has there been any other software or configuration change that could be causing this?

**Comment by blancoleandro13** [comment]
I'm using Windows 7, use SelBLocks first time, even if it does test block
gives me error, I can not boot, it does not allow me or run the first line.

Install the script in 4 different PC and got it.

2016-09-02 19:29 GMT-03:00 refactoror notifications@github.com:

**Comment by refactoror** [comment]
Can not be reproduced.
