### ISSUE TITLE
Unexpected errors after some time. Msg: TypeError: pagesets[i].getUISpecifierStringStubs is not a function

### ISSUE THREAD

**Issue by SlitEye** [refactoror/SelBlocks#31]
## Description -
There are unexpected errors after some time using Selenium IDE with SelBlocks addon:
**"Msg: TypeError: pagesets[i].getUISpecifierStringStubs is not a function"**

## Meta -
**OS:**  Windows 7 Enterprise SP1 x64
**Selenium Version:**  Selenium IDE for Firefox v2.9.1.1-signed
**Browser:**  Firefox for Windows systems
**Browser Version:**  
from Firefox 49 up to Firefox 50.0.2 (32-bit) and also Firefox 50.0.2 (64-bit)
**Language (OS | Browser: Firefox | Selenium IDE addon):** english | german | german

**Currently installed firefox and Selenium IDE addons:**
- Selenium IDE: v2.9.1.1-signed
- Selenium IDE - SelBlocks: v2.1.1-signed
- Highlight Elements (Selenium IDE): v1.22.1-signed.1-signed
- File Logging (Selenium IDE): v3.0.1-signed
- Log Search Bar (Selenium IDE): v1.22.1-signed.1-signed
- Stored Variables (Selenium IDE): v2.0.1-signed.1-signed
- Test Results (Selenium IDE): v2.0.1-signed.1-signed

**Installed addons before / in the past:**
- Selenium IDE: v2.9.1.1-signed
- Selenium IDE - SelBlocks: v2.1.1-signed
- Highlight Elements (Selenium IDE): v1.22.1-signed.1-signed
- File Logging (Selenium IDE): v3.0.1-signed
- Log Search Bar (Selenium IDE): v1.22.1-signed.1-signed
- Stored Variables (Selenium IDE): v2.0.1-signed.1-signed
- Test Results (Selenium IDE): v2.0.1-signed.1-signed
- Page Coverage (Selenium IDE): v1.15.1-signed.1-signed
- Screenshot on Fail (Selenium IDE): v1.14.1-signed.1-signed
- Selenium IDE: Selenium 2 Excel Converter: v1.0.1.1-signed.1-signed
- Selenium Wiki Formatter: v1.0.1-signed.1-signed
- Separated Values Formatter (Selenium IDE): v1.0.0.1-signed.1-signed
- WebDriver Backed Formatters: v1.0.4.1-signed.1-signed
- SeLite addons (included SelBlocks Global)

I don't know really how I can reproduce or provoke the described errors. It seems to me, that the errors appears faster if I have execute my own JS injections in my test suites. But, my JS injections are only default ECMA JS:
[ETC_Tenant_StdLib_Core.zip](https://github.com/SeleniumHQ/selenium/files/626985/ETC_Tenant_StdLib_Core.zip)

See also my related tickets at other Selenium IDE / addon projects, see: 
https://github.com/SeleniumHQ/selenium/issues/3194
https://github.com/SeLite/SelBlocksGlobal/issues/6

Please start the investigation and fix the errors, because we want SelBlocks functionallity.

Best regards, 

Kevin Marco Erler
QA at INTERSHOP Communications AG - FullService

**Comment by refactoror** [comment]
This is not a Selblocks function, and Selblocks does not call this function.
