### ISSUE TITLE
There was an unexpected error. Msg: TypeError: this._advanceToNextRow is not a function

### ISSUE THREAD

**Issue by havingfunq** [refactoror/SelBlocks#32]
Upon running the user extension, there is an error. Here is the full output.

There was an unexpected error. Msg: TypeError: this._advanceToNextRow is not a function
Url: chrome://selenium-ide/content/tools.js -> file:///C:/Users/VF/Documents/SelBlocks/user-extensions.js?1481003249523, line: 598, column: 9
nextCommand@chrome://selenium-ide/content/tools.js -> file:///C:/Users/VF/Documents/SelBlocks/user-extensions.js?1481003249523:598:9
$$.fn.interceptReplace/targetObj[targetFnName]@chrome://selenium-ide/content/tools.js -> file:///C:/Users/VF/Documents/SelBlocks/user-extensions.js?1481003249523:221:14
.nextCommand@chrome://selenium-ide/content/selenium-runner.js:217:19
TestLoop.prototype.continueTest@chrome://selenium-ide/content/selenium-core/scripts/selenium-executionloop.js:35:35
.start@chrome://selenium-ide/content/selenium-runner.js:194:5
start@chrome://selenium-ide/content/selenium-runner.js:418:3
Debugger.prototype.start@chrome://selenium-ide/content/debugger.js:154:3
Editor.prototype.playCurrentTestCase@chrome://selenium-ide/content/editor.js:925:3
Editor.prototype.playTestSuite/<@chrome://selenium-ide/content/editor.js:977:7
Editor.prototype.playTestSuite@chrome://selenium-ide/content/editor.js:973:4
Editor.controller.doCommand@chrome://selenium-ide/content/editor.js:390:9
goDoCommand@chrome://global/content/globalOverlay.js:100:7
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

What am I doing wrong? Thanks.

**Comment by refactoror** [comment]
What do you mean by "upon running the extension"?
Can I assume you installed the extension in Firefox, and the error occurs upon running a script you have written? Did you install Selblocks from [here](https://addons.mozilla.org/en-US/firefox/addon/selenium-ide-sel-blocks/)?

**Comment by refactoror** [comment]
I can see from the above stacktrace that you are not using the Firefox addon at all. I am seeing the user-extension.js, which is for Selenium Server, not for Firefox. May I suggest that you review the documentation provided on the download page.
