### ISSUE TITLE
[error] Unexpected Exception: TypeError: blockDefs is null. 

### ISSUE THREAD

**Issue by mijaz81** [refactoror/SelBlocks#34]
Firefox version:54.0.1 (32-bit)
Selenium version:025.1- signed.1 signed
SelBlocks version: 2.1

<[error] Unexpected Exception: TypeError: blockDefs is null.>

<simple authenticate user on login either logedin or invalid user>

<
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://mobility.ko-qa.frogeek.com/" />
<title>mobility-login</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">mobility-login</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/</td>
	<td></td>
</tr>
<tr>
	<td>store</td>
	<td>mijaz@test.com</td>
	<td>user1</td>
</tr>
<tr>
	<td>store</td>
	<td>mijaz</td>
	<td>pass1</td>
</tr>
<tr>
	<td>type</td>
	<td>name=email</td>
	<td>${user1}</td>
</tr>
<tr>
	<td>type</td>
	<td>//input[@type='password']</td>
	<td>${pass1}</td>
</tr>
<tr>
	<td>click</td>
	<td>css=button.login__submit</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>9000</td>
	<td></td>
</tr>
<tr>
	<td>storeText</td>
	<td>//html/body/div/div/main/div/div</td>
	<td>aa1</td>
</tr>
<tr>
	<td>storeText</td>
	<td>User was not found in the database !</td>
	<td>aa</td>
</tr>
<tr>
	<td>echo</td>
	<td>${aa2}</td>
	<td></td>
</tr>
<tr>
	<td>echo</td>
	<td>${aa1}</td>
	<td></td>
</tr>
<tr>
	<td>runScript</td>
	<td>javascript{alert(&quot;pending&quot;)}</td>
	<td></td>
</tr>
<tr>
	<td>if</td>
	<td>${aa1}='User was not found in the database !'</td>
	<td></td>
</tr>
<tr>
	<td>echo</td>
	<td>invalid credentionals</td>
	<td></td>
</tr>
<tr>
	<td>else</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>echo</td>
	<td>valid credentionals</td>
	<td></td>
</tr>
<tr>
	<td>endIf</td>
	<td></td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>

>

**Comment by refactoror** [comment]
When submitting an issue: https://github.com/refactoror/SelBlocks/issues/1

**Comment by refactoror** [comment]
Is this intended to be a comparison?
${aa1}='User was not found in the database !'
It is written as an assignment.

You may want to try: aa1=='User was not found in the database !'

**Comment by mijaz81** [comment]
Thanks, it seems my bad, will correct this.

I am stuck in a new thing after updating on firefox 57 

Unable to open or create a test case as on launch of Selenium IDE I am getting 

There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://implicit-wait/content/implicit-wait-ide.js?1505900452731, line: 185, column: 9
wrap@chrome://implicit-wait/content/implicit-wait-ide.js?1505900452731:185:9
ImplicitWait/<@chrome://implicit-wait/content/implicit-wait-ide.js?1505900452731:27:9

I dont know what to do with this, any help

**Comment by peter-lyons-kehl** [comment]
@mijaz81 ,
ImplicitWait is incompatible with SelBlocks.

**Comment by mijaz81** [comment]
I didnt use implicit wait in any test case, now even I can't create test case or open any test case. It is shown on launch of selenium IDE. @peter-kehl please see if can help me on this

**Comment by refactoror** [comment]
User error, invalid bug report.
